### ISSUE TITLE
Add We-Vibe Unite 2

### ISSUE THREAD

**Issue by gazirov** [Zero-Sploit/FlipperZero-Subghz-DB#1]
We-Vibe Unite 2
[Wevibe.zip](https://github.com/Zero-Sploit/FlipperZero-Subghz-DB/files/15179081/Wevibe.zip)

**Comment by Zero-Sploit** [comment]
post the files you want me to add not a zip file

**Comment by gazirov** [comment]
sorry but git restricts adding .sub files

![image](https://github.com/Zero-Sploit/FlipperZero-Subghz-DB/assets/151927259/d279c252-9aa5-4474-a4b3-6e5db3d4e4b2)

**Comment by Zero-Sploit** [comment]
Okay look at later today I'm a bit busy right now with other things

**Comment by Zero-Sploit** [comment]
added your files
